language: node_js
node_js:
  - "7.4"

cache:
  yarn: true
  directories:
    - node_modules

addons:
  # Saucelabs
  sauce_connect: true
  # Node 5+ requires a C++11 standard compliant compiler, so we'll use gcc.
  # See more info at https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements.
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  global:
    # Saucelabs credentials for global access (including the encrypted access key exported as SAUCE_ACCESS_KEY).
    - SAUCE_USERNAME=rodrigopandini
    - secure: "Lwh4N1K+9nUtdEiVmCuW5Fc1N2rNw7nGPoMJWs0OPKZ1ho8xrqVWnU7vQXxWfT1UXG01HcZQfoM4/N+Wn8p/Ufo2vUCTorOL43zf8At9cck7X1bAhCEyIj8raiZTdvxdhc9Cmt+OL3k4pOxtynYHHY84Da1rgkkZz5HAxkRXvYrndHmoprbCdfZF0iBRikT8Y7nuDPrSHhawj7QUG4QBrWCG62iOGuBHttsqEsbflUeuH/4hVEgCCD82eMrnP0AT9wIfropsjV3q/2GU355AHNeNpoE+nfGaT4zi/w4Jqe04/GtlyOGxZ5dU7TZKwN/o9nVMu2ZYiEJSgZ/u/P9eVWClzBISfZ2ZP/bGiOO8xrDau9Rahh9rKprBLg7l2W9f+iNG8WH9zuVQWm3Dvemgzp+jPnoPDKUkXlz6xdQFO6EBBaDVpN826IHxt9uqw55Vp9eM9fZStoNB9+XE3e8RXmM7VnEm5TTse/GCALA5NxlKy4KBeYPAdtYWfNalU2ES8Hh/Gso3AazMQ//GO73nXBrk8OLs3V6caxdqoDTbW+MaT35kTbm089a9+Cl4cfc0NrWX66U46nG2m2fu1jjgphv7tNYgsNc4cSIKi4snhETsg3yXts3IEhDsvaS0W2JGAxCpy9PZTRK1qwW6gcZTjzUafNAqTAtSTiqUlPllNZ4="
    # Firebase encrypted token env var (exported as FIREBASE_TOKEN).
    - secure: "SJ2M09Q8UReH0Zi9hLrz6UXJvq2uHdi49BKSSjcYHwuX7HHMxCsWnrTYmfw7pJUF+/r5XS+Pgt0cy+U7+UYZlRIt/deCWR8lL0HuVhOJoFnof7uExcJgmyXuqHqQsHrW0ukv4l5CfG91TlWpvs+imjSLQmNzhBTyFZlny5IYE+6OhOU/SBifwWx4JtCb9V71rDQpYhjZWUf2rJjQ6s7LEQE8R8wXhO+U1gzNwQaX1VWeJagvuinswHiIkggLAiLdZOcgaYdGitAb8MSGbpmgunGsTJma/qGdIIKWGPZMeecytZopSTeYoyea8WLI04mooGPozEkHnZ7RzEYJ/86VopP631v2Ma7D87qb0TGtRNYUxkZVop33nyTn0pl5jruzkZG+R6+caNBtojyxyqv5viOVkg9TB5a46sZ+SZlUL8drbUMq4xhCAnZNuzVrR2gsrk8YIqCyGnrFuYaqh+dS3onm55NP7ou89BFC65eN8dt27RlqVuYkaI7E0bOFPp3QyKWZL6AdoUfCF7dTVjf2BavMRbRv0JKwdb/EnwnYRCfuQBYFcI3X28M9XoDGd2U03TVBafI57fGylOIbMq94EMoMZNQQ1v4iKINGxVn2moklCk4TtsEtezn8aweQqJyGl1R64qDj+SAorrvkIiaxI0GRlC8+DFHtpUj7zPdzXug="
    # Requirement for installing Node 5+
    - CXX=g++-4.8

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

before_script:
  # Install global dependencies
  - npm install -g codecov
  - npm install -g angular-cli-ghpages
  - npm install -g firebase-tools
  - npm install coveralls

script:
  # Code style/format check with tslint.
  - npm run lint
  # Unit tests.
  - npm run test:ci
  # Run and check coverage information
  - codecov
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  # E2E tests.
  - npm run e2e:ci

after_success:
  # Deploy to Firebase
  - npm run deploy:ci

  # Deploy to GitHub Page
  # Build the project
  - ng build --prod --base-href "http://rodrigopandini.com/pismflix/"
  # Copy index page to 404 (fix for github problem)
  - cp dist/index.html dist/404.html
  # Publish the project
  - ngh --repo=https://GH_TOKEN@github.com/rodrigopandini/pismflix.git --name="Rodrigo Pandini" --email=rodrigopandini@gmail.com

notifications:
  email:
    on_success: never
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/85204183f81fd281a41c
    on_success: change
    on_failure: always
    on_start: never
